[package]
name = "ShopRunCalculator"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.1"
crossterm = "0.27"
#TODO ratatui-image = { version = "1.0.0", default-features = false, features = ["crossterm", "rustix"] }
